-- Products: spices sold in fixed-size packs (e.g. 100 g turmeric).
create table products (
    id          bigint generated by default as identity primary key,
    sku         varchar(40)    not null,
    name        varchar(200)   not null,
    description varchar(2000),
    unit        varchar(20)    not null,
    pack_size   numeric(12, 3) not null,
    active      boolean        not null default true,
    created_at  timestamp(6) with time zone not null,
    updated_at  timestamp(6) with time zone not null,
    version     bigint         not null default 0,
    constraint uk_products_sku unique (sku),
    constraint ck_products_pack_size_positive check (pack_size > 0)
);

-- Current on-hand quantity per product, counted in packs. One row per product.
create table stock_levels (
    product_id bigint primary key references products (id) on delete cascade,
    quantity   bigint not null default 0,
    updated_at timestamp(6) with time zone not null,
    version    bigint not null default 0,
    constraint ck_stock_levels_quantity_non_negative check (quantity >= 0)
);

-- Append-only ledger of every change to a stock level.
create table stock_movements (
    id              bigint generated by default as identity primary key,
    product_id      bigint       not null references products (id),
    type            varchar(20)  not null,
    quantity_change bigint       not null,
    balance_after   bigint       not null,
    reference       varchar(100),
    note            varchar(500),
    occurred_at     timestamp(6) with time zone not null,
    constraint ck_stock_movements_quantity_change_non_zero check (quantity_change <> 0),
    constraint ck_stock_movements_balance_non_negative check (balance_after >= 0)
);

create index ix_stock_movements_product_occurred on stock_movements (product_id, occurred_at desc, id desc);
